### PR TITLE
Remove restriction of 999 results in tables and update use of top query param closes #49

### LINKED ISSUE #49: Remove restriction of 999 results in tables and update use of top query param
**Describe the bug**
Several tables use the `top` query param and set it to 999; this limits the number of results for those tables consistently to return max 999 rows.

**Steampipe version (`steampipe -v`)**
v0.13.5

**Plugin version (`steampipe plugin list`)**
v0.3.0

**To reproduce**
Query the table `azuread_sign_in_report` when there are more than 999 results, and only 999 will be returned.

**Expected behavior**
Tables should return all results, even if they exceed 999.

**Additional context**

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select display_name, created_date_time from azuread_application;
+----------------------------------------------------------------------------------+---------------------------+
| display_name                                                                     | created_date_time         |
+----------------------------------------------------------------------------------+---------------------------+
| turbottest58147                                                                  | 2021-01-08T20:40:34+05:30 |
| testSubhajitSP-20200124131852                                                    | 2020-01-24T13:18:55+05:30 |
| Turbot Dev ReadOnly                                                              | 2019-07-30T14:20:14+05:30 |
| rup-testSP-20190822194017                                                        | 2019-08-22T19:40:17+05:30 |
| test-clusterSP-20190822160005                                                    | 2019-08-22T16:00:06+05:30 |
| testtagsSP-20200224115309                                                        | 2020-02-24T11:53:13+05:30 |
| a6336bb8-0450-488f-9de5-15b45f368a48                                             | 2020-05-07T15:19:23+05:30 |
| Turbot Registration                                                              | 2020-10-06T09:16:51+05:30 |
| TestImportDev                                                                    | 2020-05-29T15:33:27+05:30 |
| testSubhajitClusterSP-20200122152207                                             | 2020-01-22T15:22:10+05:30 |
| a6336bb8-0450-488f-9de5-15b45f368a48                                             | 2020-05-07T14:03:39+05:30 |
| mebautomationaccount_1bj5XsQE67Wrj79BDVmn+yH4W69GJD52bnKt6zZ4Jxk=                | 2020-02-02T09:16:19+05:30 |
| testcisv85SP-20191017180417                                                      | 2019-10-17T18:04:19+05:30 |
| testStacyIntgSP-20200330124311                                                   | 2020-03-30T12:43:16+05:30 |
| sd-test-import                                                                   | 2021-07-26T19:21:16+05:30 |
| Turbot Dev Reader                                                                | 2020-05-15T16:43:42+05:30 |
| Turbot Prod SaaS - bob-azure-sub                                                 | 2020-06-30T12:49:00+05:30 |
| a6336bb8-0450-488f-9de5-15b45f368a48                                             | 2020-05-06T17:04:41+05:30 |
| luisk8sSP-20200309185025                                                         | 2020-03-10T03:20:28+05:30 |
| Turbot Staging                                                                   | 2020-03-18T01:15:22+05:30 |
| azure-cli-2020-06-23-14-09-55                                                    | 2020-06-23T19:39:57+05:30 |
| Azure AD SAML Integration                                                        | 2020-07-02T12:31:46+05:30 |
| testSubhajitSP-20200116153655                                                    | 2020-01-16T15:36:57+05:30 |
| azure-cli-2020-06-23-11-52-09                                                    | 2020-06-23T17:22:11+05:30 |
| site-reco-svh-asr-automationaccount_ROT2NiJvXlzfPe6BVm3oEWckqHh3zmlnXn/aJQwHg8Y= | 2021-07-30T14:24:26+05:30 |
| turbottest76198                                                                  | 2020-11-02T23:46:19+05:30 |
| TestClusterSubhajitSP-20200122124704                                             | 2020-01-22T12:47:06+05:30 |
| alpha-clusterSP-20190826182004                                                   | 2019-08-26T18:20:06+05:30 |

```

```
> select display_name, created_date_time from azuread_application where display_name = 'Turbot Expediters';
+-------------------+---------------------------+
| display_name      | created_date_time         |
+-------------------+---------------------------+
| Turbot Expediters | 2020-04-20T20:47:30+05:30 |
+-------------------+---------------------------+
```

```
> select count(*) from azuread_sign_in_report;
+-------+
| count |
+-------+
| 3415  |
+-------+
```
</details>

### CODE REVIEW

File: azuread/table_azuread_application.go [hunk 1]
```diff
@@ -77,10 +77,7 @@ func listAdApplications(ctx context.Context, d *plugin.QueryData, _ *plugin.Hydr
 	client := msgraph.NewApplicationsClient(session.TenantID)
 	client.BaseClient.Authorizer = session.Authorizer
 
-	// As per our test result we have set the max limit to 999
```
Comment (cbruno10) [inline azuread/table_azuread_application.go:80]: @ParthaI Was this change tested for this table, or for any other tables, where there were results over 999 and we got back all of them correctly? How does the hamilton SDK we're using handle large data sets and pagination?

File: azuread/table_azuread_application.go [hunk 2]
```diff
@@ -93,13 +90,6 @@ func listAdApplications(ctx context.Context, d *plugin.QueryData, _ *plugin.Hydr
 		input.Filter = strings.Join(filter, " and ")
 	}
 
-	limit := d.QueryContext.Limit
```
Comment (cbruno10) [inline azuread/table_azuread_application.go:96]: This seems like it may still be useful, i.e., a user asks for only 20 results, so we should only ask the Graph API for 20 results. Is there a reason we shouldn't have this code in?

**Review by cbruno10 — COMMENTED** [review]
Please see questions, thanks!

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Is the `top` query param also supposed for directory roles and identities? If so, can you please add support to those tables as well?

**Comment by ParthaI** [comment]
> @ParthaI Is the `top` query param also supposed for directory roles and identities? If so, can you please add support to those tables as well?

@cbruno10 The list API for directory roles and identities does not support `odata.query` as a parameter in the hamilton SDK, It takes the only context as a parameter.

**Review by cbruno10 — APPROVED** [review]
