### PR TITLE
Fixed adding 'Order by' or 'Group by' keywords to query results with Error Closes #109

### LINKED ISSUE #109: Adding 'Order by' or 'Group by' keywords to query results with Error
**Describe the bug**
Adding 'order by' or 'group by' keywords to query ends with:
```
Error: rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
v0.19.5

**Plugin version (`steampipe plugin list`)**
0.9.0

**To reproduce**
Working SQL:
```
select
        targetResources ->> 'id' as TargetId,
        auditLogs.activity_date_time as LogTimestamp
from
        azuread_directory_audit_report as auditLogs,
        jsonb_array_elements(auditLogs.additional_Details) as additionalDetails,
        jsonb_array_elements(auditLogs.target_resources) as targetResources
where
        auditLogs.activity_display_name = 'Exchange token'
        and auditLogs.result = 'success'
limit 10
```
Output:
```
+--------------------------------------+---------------------------+
| targetid                             | logtimestamp              |
+--------------------------------------+---------------------------+
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 255ffbbc-4514-4499-9132-4bac8727b314 | 2023-05-08T12:18:54+02:00 |
| 9696f784-1819-4bc9-9325-5ac2206b4682 | 2023-05-08T12:18:44+02:00 |
| 9696f784-1819-4bc9-9325-5ac2206b4682 | 2023-05-08T12:18:44+02:00 |
+--------------------------------------+---------------------------+
```

Broken SQL:
```
select
        targetResources ->> 'id' as TargetId,
        auditLogs.activity_date_time as LogTimestamp
from
        azuread_directory_audit_report as auditLogs,
        jsonb_array_elements(auditLogs.additional_Details) as additionalDetails,
        jsonb_array_elements(auditLogs.target_resources) as targetResources
where
        auditLogs.activity_display_name = 'Exchange token'
        and auditLogs.result = 'success'
order by
        LogTimestamp
limit 10
```
Output:
```
Error: rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime (SQLSTATE HV000)
```

**Expected behavior**
Adding those keywords shouldn't end with error.

**Additional context**
I use client secret authentication (copy of azuread.spc):
```
connection "azuread" {
  plugin = "azuread"
  tenant_id = "guid"
  client_id = "guid"
  client_secret = "secret"
}
```

Added scopes to the application in AAD:
- AuditLog.Read.All
- Directory.Read.All
- User.Read.All

But something like that works perfectly:
```
select 
	id, 
	title 
from 
	azuread_user 
order by 
	id 
limit 10
```

Output from logs (database.log):
```
2023-05-08 10:41:46.509 UTC [WARN]  hub: stream receive error rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime (0xc000212d80)
2023-05-08 10:41:46.509 UTC [2272] ERROR:  rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime
2023-05-08 10:41:46.509 UTC [2272] STATEMENT:  select
	        targetResources ->> 'id' as TargetId,
	        auditLogs.activity_date_time as LogTimestamp
	from
	        azuread_directory_audit_report as auditLogs,
	        jsonb_array_elements(auditLogs.additional_Details) as additionalDetails,
	        jsonb_array_elements(auditLogs.target_resources) as targetResources
	where
	        auditLogs.activity_display_name = 'Exchange token'
	        and auditLogs.result = 'success'
	order by
	        LogTimestamp
	limit 10
2023-05-08 10:41:48.762 UTC [2270] LOG:  could not receive data from client: Connection reset by peer
2023-05-08 10:41:48.762 UTC [2270] LOG:  disconnection: session time: 0:01:59.995 user=root database=steampipe host=127.0.0.1 port=34206
2023-05-08 10:41:48.762 UTC [2269] LOG:  could not receive data from client: Connection reset by peer
2023-05-08 10:41:48.762 UTC [2269] LOG:  disconnection: session time: 0:02:00.010 user=root database=steampipe host=127.0.0.1 port=34192

```

Output from logs (plugin.log)
```
2023-05-08 10:41:33.615 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: waitForPendingItem timed out waiting for pending transfer (azuread-1683542473956) 0xc016c5cc90 indexBucketKey: index__azuread_azuread_directory_audit_report, item key azuread_azuread_directory_audit_report_--activity_display_name-=-Exchange token---activity_display_name-=-Exchange token--activity_display_name-=-Exchange token-result-=-success-activity_display_name-=-Exchange token-result-=-success_activity_date_time,additional_details,target_resources,activity_display_name,result_-1
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: recovered a panic from a wrapped hydrate function: interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: stack: goroutine 91245 [running]:
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: doList callHydrateWithRetries (azuread-1683542473956) returned err rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: QueryData StreamError rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime (azuread-1683542473956)
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: streamRows for azuread-1683542473956 - execution has failed (rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime) - calling queryCache.AbortSet
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: executeForConnection azuread returned error rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime
2023-05-08 10:41:46.508 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1683542473956: error channel received rpc error: code = Internal desc = hydrate function listAdDirectoryAuditReports failed with panic interface conversion: *models.SignIn is not models.DirectoryAuditable: missing method GetActivityDateTime

```

I've tried same query but on other AAD tenant (same AAD application scopes) and works perfectly.

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

File: azuread/table_azuread_sign_in_report.go [hunk 1]
```diff
@@ -106,9 +106,9 @@ func listAdSignInReports(ctx context.Context, d *plugin.QueryData, _ *plugin.Hyd
 	}
 
 	err = pageIterator.Iterate(ctx, func(pageItem interface{}) bool {
-		signIn := pageItem.(models.SignInable)
-
-		d.StreamListItem(ctx, &ADSignInReportInfo{signIn})
+		if signIn, ok := pageItem.(models.SignInable); ok {
```
Comment (cbruno10) [inline azuread/table_azuread_sign_in_report.go:109]: Can you please add a comment mentioning the other model type we can get here? It will help explain why we're doing a type check here

**Review by cbruno10 — APPROVED** [review]
